version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn checkstyle:check
      - run: mvn test
      - run: mvn post-site
      - store_artifacts:
          path: target
      - codecov/upload

workflows:
  test:
    jobs:
      - test:
        filters:
          branches:
            only: master