version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn test

workflows:
  test:
    jobs:
      - test:
        filters:
          branches:
            only: master
