version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn checkstyle:check
      - run: mvn test
      - run: mvn post-site
      - store_artifacts:
          path: target
      - codecov/upload

  docs-build:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn javadoc:javadoc
      - persist_to_workspace:
          root: .
          paths:
            - target

  docs-deploy:
    docker:
      - image: node:16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:y1SnBocJEyH1MNG19hIpWeS5um0wEtzBE23j14MgkhI"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g gh-pages@2.0.1
            git config user.email "cantin.prat@alumni.univ-avignon.fr"
            git config user.name "cantin.prat"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/apidocs

workflows:
  test:
    jobs:
      - test:
        filters:
          branches:
            only: master
      - docs-build:
          requires:
            - test
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master